[package]
name = "instistats"
version = "0.1.0"
authors = ["Ben Morrison <ben@gbmor.dev>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
serde_yaml = "0.8"
walkdir = "2.2"

[dependencies.serde]
version = "1.0"
features = ["derive"]
